# Generated by Django 4.0.3 on 2022-03-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_scopes_article_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='scope',
        ),
    ]
