# Generated by Django 4.0.3 on 2022-03-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_articlescope_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='scope',
            new_name='scopes',
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.scope'),
        ),
    ]
