# Generated by Django 4.0.3 on 2022-03-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_rename_scope_article_scopes_alter_articlescope_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescope',
            name='is_main',
        ),
        migrations.AddField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
